# Generated by Django 2.1.3 on 2018-11-06 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Pubg Profile', 'verbose_name_plural': 'Pubg Profiles'},
        ),
    ]
