# Generated by Django 2.1.3 on 2018-11-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181106_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pubg_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Pubg ID'),
        ),
    ]
