# Generated by Django 2.1.3 on 2018-12-02 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City Name')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Map Name')),
                ('genre', models.CharField(blank=True, choices=[('am', 'AMBUSH'), ('sn', 'SNIPING'), ('as', 'ASSAULT'), ('st', 'STEALTH')], max_length=255)),
                ('short_desc', models.TextField(verbose_name='Short Description')),
                ('long_desc', models.TextField(verbose_name='Long Description')),
            ],
            options={
                'verbose_name_plural': 'Maps',
            },
        ),
        migrations.CreateModel(
            name='MapImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='map_pics', verbose_name='Images')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapsNguns.Map')),
            ],
            options={
                'verbose_name_plural': 'Map Images',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Vehicle Name')),
                ('is_drivable', models.BooleanField(default=True, verbose_name='Is Drivable')),
                ('capacity', models.PositiveIntegerField(verbose_name='No. of seats')),
                ('desc', models.TextField(verbose_name='Description')),
                ('maps', models.ManyToManyField(to='mapsNguns.Map')),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Weapon Name')),
                ('desc', models.TextField(verbose_name='Weapon Description')),
                ('damage', models.PositiveIntegerField(verbose_name='Damage level out of 5')),
                ('maps', models.ManyToManyField(to='mapsNguns.Map')),
            ],
            options={
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.CreateModel(
            name='WeaponImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gun_pics', verbose_name='Images')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapsNguns.Weapon')),
            ],
            options={
                'verbose_name_plural': 'Weapon Images',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapsNguns.Map'),
        ),
    ]
