# Generated by Django 2.1.3 on 2018-12-02 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapsNguns', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weaponimage',
            old_name='map',
            new_name='weapon',
        ),
    ]
